In [2]:
# test - train split
# pipeline
# BoW
# tf-idf
# vocab size
#** convert the df to sentiment class rating 1,2 = 0 and 5 = 1
# shuffle data
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

c:\users\me\appdata\local\programs\python\python37\lib\site-packages\matplotlib\__init__.py:886: MatplotlibDeprecationWarning:
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))

In [3]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer
from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_pickle("./pickles/preProcessed.pkl")

In [7]:
df['Rating'].value_counts()

5    12540
4     4908
3     2823
2     1549
1      821
Name: Rating, dtype: int64

In [8]:
df.columns

Index(['Review Text', 'Rating', 'Recommended IND'], dtype='object')

In [42]:
df_filtered = pd.DataFrame()

In [14]:
df[(df["Rating"] == 1) | (df["Rating"] == 2)].count()

Review Text        2370
Rating             2370
Recommended IND    2370
dtype: int64

In [43]:
df_filtered = df[df['Rating'] == 5].head(3000)

In [44]:
df_filtered.(df[(df["Rating"] == 1) | (df["Rating"] == 2)],ignore_index=True)

,Review Text,Rating,Recommended IND
0,love dress 's soon pretty happened find store ...,5,1
1,love love love jumpsuit 's fun flirt fabulous ...,5,1
2,shirt flattering due adjustable front tie perf...,5,1
3,added basket last minute see would look like p...,5,1
4,love dress usually get runs little snug bust o...,5,1
5,'m 5 '' 5 125 les ordered petite make sure len...,5,1
6,dress perfection pretty flattering,5,1
7,find radiant reviews written navvy shippers pa...,5,1
8,ought black go larkspur mid dress n't bother l...,5,1
9,took chance louse glad n't crazy louse photogr...,5,1
10,flattering super copy coat work well cold dry ...,5,1
11,love look feel tell dress looking something di...,5,1
12,love shirt first saw n't sure shirt dress sinc...,5,1
13,several goodhyouman shirts get many compliment...,5,1
14,sweeter come classic balances quickly hand-kni...,5,1
15,beautifully made parts trend flared crop much ...,5,1
16,never would given parts second look online per...,5,1
17,parts even better person downside need dry cle...,5,1
18,neat dress color great fabric super soft tall ...,5,1
19,must ordered small 5'6 '' 135 size 4 medium mo...,5,1
20,super cut come pull seizing accurate material ...,5,1
21,great casual top flare looks cut grey micro se...,5,1
22,beautiful top 's unique ordinary bought usual ...,5,1
23,porch cut love plaid check design colors look ...,5,1
24,cried today local retailer comfortable flatter...,5,1
25,love top wear time problem tell wear time fabr...,5,1
26,comfortable material good cut sleeves flattering,5,1
27,sweeter perfect fall ... 's room warm super co...,5,1
28,really cut top embroidery collar big top beaut...,5,1
29,absolutely love big 's probably favorite retai...,5,1
...,...,...,...
5340,n't work looks better snipped piece made look ...,2,0
5341,love colors however 200 lot pay small piece fa...,1,0
5342,shocked receive dress rusty nipper looks like ...,1,0
5343,n't whole lot like dress shoulders large hours...,2,0
5344,'m disappointed dress n't work ordered size me...,1,0
5345,excited get sweeter mail unfortunately sweeter...,2,0
5346,well made dress much fabric taste lays little ...,2,0
5347,attracted feminine design dress silhouette flo...,2,0
5348,loved looked model however tried store greatly...,2,0
5349,excited simon thought colors would lovely look...,2,0
5350,wanted love dress however shape also somewhat ...,2,0
5351,dress much potential horizontal knit ruined tr...,2,0
5352,thought dress looked gorgeous model float ligh...,2,0
5353,wants overpriced uncomfortable utter dismay wo...,1,0
5354,'m 5'7 '' 155lbs ordered large fit arms awkwar...,1,0
5355,reading 2 reviews decided order usual size 26 ...,2,1
5356,gorgeous print found fussy taste quite shapele...,2,0
5357,love look dress runs large 5'2 110lbs ordered ...,2,1
5358,'ve looking nice summer maxim dress reading po...,2,0
5359,loved print fabric dress first saw trying diff...,1,0
5360,love dress return sleeves tight never problem ...,2,1
5361,wanted love top ordered `` blue '' blue orange...,2,0
5362,unfortunately dress work like reviews 5'8 130l...,2,0
5363,model looks awesome cut top looked body tight ...,2,0
5364,'m petite knew buying would big sweeter look p...,2,0
5365,excited find fun lightweight white dress sprin...,1,0
5366,ordered noted reviews said sheer thought would...,2,0
5367,drew shirt beautiful silver gold embroidery fr...,2,0
5368,dress cut photo fit true size material slink f...,2,0
5369,surprised positive reviews product terrible cu...,1,0

In [45]:
df_filtered = df_filtered.sample(frac=1).reset_index(drop=True)

In [46]:
df_filtered.tail()

,Review Text,Rating,Recommended IND
2995,fence getting maxim 's prices ended scoring re...,5,1
2996,usually 8 10 8 skirt nice many soft colors go ...,5,1
2997,hard believe called chemise fabulous dress dre...,5,1
2998,yes big also amazing soft colors great hood we...,5,1
2999,love top got sale glad short still super flatt...,5,1

In [1]:
#try with tf-idf, BoW, PPMI\
#logistic, SVM, niave Bayes
#pipeline